import { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { PropsWithChildren } from 'react'

import styles from './layout.module.scss'

const inter = Inter({ subsets: ['latin'] })

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const Layout = ({ children }: PropsWithChildren) => (
  <html lang='en'>
    <body className={[inter.className, styles.body].join(' ')}>{children}</body>
  </html>
)

export { Layout as default, metadata }
