import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ReactNode } from 'react'

import styles from './layout.module.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function Layout({ children }: { children: ReactNode }) {
  return (
    <html lang='en'>
      <body className={[inter.className, styles.body].join(' ')}>{children}</body>
    </html>
  )
}
